### ISSUE TITLE
Please don't mutate String.prototype

### ISSUE THREAD

**Issue by timoxley** [tallesl/format-unicorn#1]
Mutating the global native prototypes breaks the package isolation built into node's module system. If two packages load two different versions of `format-unicorn`, which version of the function is used? It will be determined at runtime, whichever loads last.

Ideally, this package just exports a function and has no application-wide side-effects.

If someone wants to add this to their `String.prototype` they can just do this:

```js
String.prototype.formatUnicorn = require('format-unicorn')
```

By simply exporting a function you're not forcing this addition through the entire system.

**Comment by tallesl** [comment]
It *felt* wrong messing with String's prototype, now I *know* that is.
I've made a `/safe` version just like [colors.js](https://github.com/Marak/colors.js) (looks like they problems with it just as you've stated [*](https://github.com/Marak/colors.js/issues/5) [*](https://github.com/Marak/colors.js/issues/16) [*](https://github.com/Marak/colors.js/issues/41) [*](https://github.com/Marak/colors.js/issues/62) ).

Btw, ty for stopping by :)
